export const EPISODE_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "id",
    "topic",
    "domain",
    "title",
    "claim",
    "mechanism",
    "caveat",
    "confidence",
    "sources",
    "spokenScript",
    "wordCount",
    "durationSeconds",
    "aspectRatio",
    "hook",
    "body",
    "payoff",
    "captions",
    "shots",
    "onScreenText",
    "qaNotes",
  ],
  properties: {
    id: { type: "string" },
    topic: { type: "string" },
    domain: { type: "string" },
    title: { type: "string" },
    claim: { type: "string" },
    mechanism: { type: "string" },
    caveat: { type: "string" },
    confidence: { type: "string", enum: ["high", "medium", "low"] },
    sources: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["title", "url"],
        properties: {
          title: { type: "string" },
          url: { type: "string" },
        },
      },
    },
    spokenScript: { type: "string" },
    wordCount: { type: "number" },
    durationSeconds: { type: "number" },
    aspectRatio: { type: "string", enum: ["9:16", "16:9"] },
    hook: { type: "string" },
    body: { type: "string" },
    payoff: { type: "string" },
    captions: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["t", "text"],
        properties: {
          t: { type: "string" },
          text: { type: "string" },
        },
      },
    },
    shots: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "durationSeconds",
          "role",
          "firstFrame",
          "motion",
          "audio",
          "imaginePrompt",
        ],
        properties: {
          id: { type: "string" },
          durationSeconds: { type: "number" },
          role: { type: "string", enum: ["hook", "mechanism", "payoff"] },
          firstFrame: { type: "string" },
          motion: { type: "string" },
          audio: { type: "string" },
          imaginePrompt: { type: "string" },
        },
      },
    },
    onScreenText: { type: "array", items: { type: "string" } },
    qaNotes: { type: "string" },
  },
} as const;
